version: "3"

services:
  db:
    image: mysql:5.7 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: clothing_store
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  web:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db